/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData airplanemode_active =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_1 =
      IconData(0xf0ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fighter_jet =
      IconData(0xf0fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_africa =
      IconData(0xf57c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_americas =
      IconData(0xf57d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_asia =
      IconData(0xf57e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane_arrival =
      IconData(0xf5af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane_departure =
      IconData(0xf5b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_europe =
      IconData(0xf7a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_circled =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
